/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRouteImport } from './routes/_authenticated/grade-r-ready-updates/src/routes/_authenticated/activities'
import { Route as AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRouteImport } from './routes/_authenticated/grade-r-ready-updates/src/routes/_authenticated/checklist'
import { Route as AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRouteImport } from './routes/_authenticated/grade-r-ready-updates/src/routes/_authenticated/progress'
import { Route as AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRouteImport } from './routes/_authenticated/grade-r-ready-updates/src/routes/_authenticated/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute =
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRouteImport.update(
    {
      id: '/grade-r-ready-updates/src/routes/_authenticated/activities',
      path: '/grade-r-ready-updates/src/routes/activities',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute =
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRouteImport.update(
    {
      id: '/grade-r-ready-updates/src/routes/_authenticated/checklist',
      path: '/grade-r-ready-updates/src/routes/checklist',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute =
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRouteImport.update(
    {
      id: '/grade-r-ready-updates/src/routes/_authenticated/progress',
      path: '/grade-r-ready-updates/src/routes/progress',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute =
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRouteImport.update(
    {
      id: '/grade-r-ready-updates/src/routes/_authenticated/report',
      path: '/grade-r-ready-updates/src/routes/report',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/report': typeof AuthenticatedReportRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/grade-r-ready-updates/src/routes/activities': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute
  '/grade-r-ready-updates/src/routes/checklist': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute
  '/grade-r-ready-updates/src/routes/progress': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute
  '/grade-r-ready-updates/src/routes/report': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/report': typeof AuthenticatedReportRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/grade-r-ready-updates/src/routes/activities': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute
  '/grade-r-ready-updates/src/routes/checklist': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute
  '/grade-r-ready-updates/src/routes/progress': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute
  '/grade-r-ready-updates/src/routes/report': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/activities': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute
  '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/checklist': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute
  '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/progress': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute
  '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/report': typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activities'
    | '/checklist'
    | '/dashboard'
    | '/progress'
    | '/report'
    | '/setup'
    | '/grade-r-ready-updates/src/routes/activities'
    | '/grade-r-ready-updates/src/routes/checklist'
    | '/grade-r-ready-updates/src/routes/progress'
    | '/grade-r-ready-updates/src/routes/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activities'
    | '/checklist'
    | '/dashboard'
    | '/progress'
    | '/report'
    | '/setup'
    | '/grade-r-ready-updates/src/routes/activities'
    | '/grade-r-ready-updates/src/routes/checklist'
    | '/grade-r-ready-updates/src/routes/progress'
    | '/grade-r-ready-updates/src/routes/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activities'
    | '/_authenticated/checklist'
    | '/_authenticated/dashboard'
    | '/_authenticated/progress'
    | '/_authenticated/report'
    | '/_authenticated/setup'
    | '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/activities'
    | '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/checklist'
    | '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/progress'
    | '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/activities': {
      id: '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/activities'
      path: '/grade-r-ready-updates/src/routes/activities'
      fullPath: '/grade-r-ready-updates/src/routes/activities'
      preLoaderRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/checklist': {
      id: '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/checklist'
      path: '/grade-r-ready-updates/src/routes/checklist'
      fullPath: '/grade-r-ready-updates/src/routes/checklist'
      preLoaderRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/progress': {
      id: '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/progress'
      path: '/grade-r-ready-updates/src/routes/progress'
      fullPath: '/grade-r-ready-updates/src/routes/progress'
      preLoaderRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/report': {
      id: '/_authenticated/grade-r-ready-updates/src/routes/_authenticated/report'
      path: '/grade-r-ready-updates/src/routes/report'
      fullPath: '/grade-r-ready-updates/src/routes/report'
      preLoaderRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute: typeof AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute:
    AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedActivitiesRoute,
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute:
    AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedChecklistRoute,
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute:
    AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedProgressRoute,
  AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute:
    AuthenticatedGradeRReadyUpdatesSrcRoutesAuthenticatedReportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
